// shared/types/settings.ts

export interface AppSettings {
  general: GeneralSettings;
  gmail: GmailSettings;
  ai: AISettings;
  wordpress: WordPressSettings;
  article: ArticleSettings;
  ui: UISettings;
  notifications: NotificationSettings;
}

export interface GeneralSettings {
  language: 'pl' | 'en';
  theme: 'light' | 'dark' | 'auto';
  autoSave: boolean;
  autoSaveInterval: number; // minutes
  maxFileSize: number; // MB
  supportedFormats: string[];
  dataRetention: number; // days
}

export interface GmailSettings {
  autoRefresh: boolean;
  refreshInterval: number; // minutes
  defaultFilters: EmailFilters;
  maxEmailsPerPage: number;
  showUnreadOnly: boolean;
  autoMarkAsRead: boolean;
  downloadAttachments: boolean;
  attachmentSizeLimit: number; // MB
}

export interface AISettings {
  defaultModel: 'gpt-4' | 'gpt-3.5-turbo' | 'claude-3';
  temperature: number;
  maxTokens: number;
  defaultLanguage: 'pl' | 'en';
  autoAnalyze: boolean;
  confidenceThreshold: number;
  promptTemplates: AIPrompt[];
  customPrompts: AIPrompt[];
}

export interface WordPressSettings {
  defaultSite: string;
  autoPublish: boolean;
  defaultStatus: 'publish' | 'draft' | 'private';
  defaultCategory: number;
  defaultTags: number[];
  featuredImageSettings: FeaturedImageSettings;
  seoSettings: SEOSettings;
  contentSettings: ContentSettings;
}

export interface FeaturedImageSettings {
  autoSetFeatured: boolean;
  defaultAltText: string;
  defaultCaption: string;
  resizeForWeb: boolean;
  maxWidth: number;
  maxHeight: number;
  quality: number;
}

export interface SEOSettings {
  autoGenerateTitle: boolean;
  autoGenerateDescription: boolean;
  autoGenerateKeywords: boolean;
  titleTemplate: string;
  descriptionTemplate: string;
  keywordsTemplate: string;
  focusKeyword?: string;
}

export interface ContentSettings {
  autoFormatContent: boolean;
  removeEmailHeaders: boolean;
  addReadMore: boolean;
  defaultExcerptLength: number;
  autoAddTags: boolean;
  autoAddCategories: boolean;
}

export interface ArticleSettings {
  defaultTitle: string;
  defaultCategory: string;
  defaultTags: string[];
  autoGenerateSlug: boolean;
  slugTemplate: string;
  exportFormats: ('html' | 'markdown' | 'json')[];
  defaultExportFormat: 'html' | 'markdown' | 'json';
  imageProcessing: ImageProcessingOptions;
  contentTemplates: ContentTemplate[];
}

export interface ImageProcessingOptions {
  maxWidth: number;
  maxHeight: number;
  quality: number;
  format: 'jpeg' | 'png' | 'webp';
  optimize: boolean;
  generateThumbnails: boolean;
}

export interface ContentTemplate {
  id: string;
  name: string;
  content: string;
  isDefault: boolean;
  variables: string[];
}

export interface UISettings {
  sidebarCollapsed: boolean;
  showTooltips: boolean;
  showKeyboardShortcuts: boolean;
  animationsEnabled: boolean;
  compactMode: boolean;
  fontSize: 'small' | 'medium' | 'large';
  colorScheme: 'default' | 'high-contrast' | 'colorblind-friendly';
}

export interface NotificationSettings {
  emailNotifications: boolean;
  desktopNotifications: boolean;
  soundEnabled: boolean;
  notificationTypes: {
    emailFetched: boolean;
    aiAnalysisComplete: boolean;
    articleCreated: boolean;
    wordpressUploaded: boolean;
    errorOccurred: boolean;
  };
  notificationDuration: number; // seconds
}

export interface SettingsUpdateRequest {
  section: keyof AppSettings;
  settings: Partial<AppSettings[keyof AppSettings]>;
}

export interface SettingsUpdateResponse {
  success: boolean;
  message?: string;
  error?: string;
}

export interface SettingsExportRequest {
  includeSensitiveData: boolean;
  format: 'json' | 'yaml';
}

export interface SettingsExportResponse {
  success: boolean;
  data?: string;
  error?: string;
}

export interface SettingsImportRequest {
  data: string;
  format: 'json' | 'yaml';
  overwrite: boolean;
}

export interface SettingsImportResponse {
  success: boolean;
  importedSections: string[];
  errors: string[];
}

// Import types from other modules
import { EmailFilters } from './email';
import { AIPrompt } from './ai'; 